name: kathaappa
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  like_button: ^2.0.5

  cupertino_icons: ^1.0.2
  firebase_core: ^2.1.1
  firebase_auth: ^4.1.1
  provider: ^6.0.3
  cloud_firestore: ^4.0.4
  shared_preferences: ^2.0.15
  font_awesome_flutter: ^10.1.0
  connectivity_plus: ^3.0.2
  http: ^0.13.4
  hexcolor: ^3.0.1
  intl: ^0.17.0
  firebase_storage: ^11.0.4
  fluttertoast: ^8.1.1
  path_provider: ^2.0.11
  flame: ^1.7.3
  image_picker: ^0.8.6+1
  flutter_svg: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/logo.jpg
    - assets/gameAssets/selectionPage.png
    - assets/gameAssets/man.png
    - assets/background2.png
    - assets/addImage.png
    - assets/gameAssets/balla.gif
    - assets/gameAssets/eluwa.gif
    - assets/gameAssets/gemba.gif
    - assets/gameAssets/hawa.gif
    - assets/gameAssets/ibba.gif
    - assets/gameAssets/makuluwa.gif
    - assets/gameAssets/samanalaya.gif
    - assets/screenTestAssets/HomeScreen.gif
    - assets/screenTestAssets/wordListBack.jpg
    - assets/screenTestAssets/DogList.gif
    - assets/screenTestAssets/GoatList.gif
    - assets/screenTestAssets/icon-home.png
    - assets/screenTestAssets/icon-profile.png
    - assets/screenTestAssets/icon-back.png
    - assets/screenTestAssets/SpiderList.gif
    - assets/screenTestAssets/DogIn.gif
